/*
 * This source file was generated by the Gradle 'init' task
 */
package org.orpheus;

public class App {
  public String getGreeting() {
    return "Hello Java!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    new RecordAudio().hello("This class will handle recording desktop audio.");
  }
}
